version: '3'
services:
  logs_upload:
    image: yangyueguang/flask:2020042615
    restart: always
    ports:
      - 8000:5001
    volumes:
      - ./data/logs:/app/logs
    environment:
      - WORKERS=2
      - THREADS=2

