version: '3'
services:
  logs_upload:
    image: dockerhub.datagrand.com/zz57/logs_upload:2019112610
#    command: python3 run.py runserver -h 0.0.0.0 -p 5001 --threaded
    restart: always
    ports:
      - 18002:5001
    volumes:
      - ./data/logs:/apps/logs
      - ./data/time_report_interval.txt:/apps/static/time_report_interval.txt
    environment:
      # 访问的是idps的是deploy_idps_extract服务，根据暴露的端口打洞到本地
      - IDPS_HOST=127.0.0.1
      - IDPS_PORT=15800
      # 访问的是部署ocr服务的服务器地址与暴露的端口
      - OCR_HOST=100.100.22.62
      - OCR_PORT=51000
      # 访问的是搜索部署的服务器地址 docker service ls | grep pangu_online
      - SEARCH_HOST=100.100.22.62
      - SEARCH_PORT=39388
      # 前端给的上传汇总数据的地址
      - MERGE_HOST=unionsw.com
      - MERGE_PORT=8101
      # 统计信息 es_ip和es_port 现在都是打洞到本地，ip是同一个ip，端口可以根据docker ps|grep nlp查看各个服务的端口
      - NLP_HOST_TONGJI=127.0.0.1
      - NLP_PORT_TONGJI=19234
      - NLP_HOST_TEXT_PROCESS=127.0.0.1
      - NLP_PORT_TEXT_PROCESS=18001
      - NLP_HOST_PREPROCESS=127.0.0.1
      - NLP_PORT_PREPROCESS=18000
      - NLP_HOST_TAGGING=127.0.0.1
      - NLP_PORT_TAGGING=9190
      - NLP_HOST_SUMMARY=127.0.0.1
      - NLP_PORT_SUMMARY=8879
      - NLP_HOST_KNOWLEDGE=127.0.0.1
      - NLP_PORT_KNOWLEDGE=8565
      #idps的服务地址和用户名密码
      - IDPS_LOGIN_HOST=127.0.0.1
      - IDPS_LOGIN_PORT=15002
      - IDPS_USERNAME=superadminpro
      - IDPS_PASSWORD=BEgPDsMumFlc
      - RELOGIN_INTERVAL=3600
      - PROCESS_NUM=1
      - SCAN_TIME_INTERVAL=6

